/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'country' : string,
  'imageUrls' : Array<string>,
  'name' : string,
  'durationHours' : number,
  'description' : string,
  'destinationCity' : string,
  'availableSpots' : bigint,
  'category' : string,
  'rating' : number,
  'price' : number,
}
export interface Analytics {
  'dormBookings' : bigint,
  'hotelBookings' : bigint,
  'totalBookings' : bigint,
  'flightBookings' : bigint,
  'totalRevenue' : number,
  'activityBookings' : bigint,
}
export interface Booking {
  'id' : bigint,
  'status' : string,
  'activityDate' : [] | [bigint],
  'listingId' : bigint,
  'user' : Principal,
  'checkInDate' : [] | [bigint],
  'listingType' : ListingType,
  'bookingDate' : bigint,
  'checkOutDate' : [] | [bigint],
  'totalPrice' : number,
  'numGuestsOrSeats' : bigint,
}
export interface Destination {
  'id' : bigint,
  'lat' : number,
  'lon' : number,
  'timezone' : string,
  'country' : string,
  'oxygenLevel' : number,
  'city' : string,
  'altitude' : bigint,
  'description' : string,
}
export interface Dorm {
  'id' : bigint,
  'country' : string,
  'imageUrls' : Array<string>,
  'pricePerNight' : number,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'rating' : number,
  'location' : string,
  'bedTypes' : Array<string>,
}
export interface Flight {
  'id' : bigint,
  'arrivalDateTime' : bigint,
  'flightClass' : string,
  'flightNumber' : string,
  'destinationCity' : string,
  'availableSeats' : bigint,
  'airline' : string,
  'price' : number,
  'departureDateTime' : bigint,
  'originCity' : string,
}
export interface Hotel {
  'id' : bigint,
  'roomTypes' : Array<string>,
  'availableRooms' : bigint,
  'country' : string,
  'imageUrls' : Array<string>,
  'pricePerNight' : number,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'rating' : number,
  'location' : string,
}
export interface ItineraryDay {
  'date' : bigint,
  'activities' : Array<string>,
  'dayNumber' : bigint,
  'notes' : string,
}
export type ListingType = { 'hotel' : null } |
  { 'flight' : null } |
  { 'dorm' : null } |
  { 'activity' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Trip {
  'id' : bigint,
  'destination' : string,
  'tripName' : string,
  'endDate' : bigint,
  'user' : Principal,
  'itineraryDays' : Array<ItineraryDay>,
  'startDate' : bigint,
}
export interface UserProfile {
  'displayName' : string,
  'role' : UserRole,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItineraryDay' : ActorMethod<
    [bigint, bigint, bigint, Array<string>, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      number,
      Array<string>,
      bigint,
    ],
    bigint
  >,
  'createBooking' : ActorMethod<
    [
      ListingType,
      bigint,
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      bigint,
      number,
    ],
    bigint
  >,
  'createDorm' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      number,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
  'createFlight' : ActorMethod<
    [string, string, string, bigint, bigint, number, string, bigint, string],
    bigint
  >,
  'createHotel' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      number,
      Array<string>,
      Array<string>,
      bigint,
      Array<string>,
    ],
    bigint
  >,
  'createTrip' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'deleteActivity' : ActorMethod<[bigint], undefined>,
  'deleteDorm' : ActorMethod<[bigint], undefined>,
  'deleteFlight' : ActorMethod<[bigint], undefined>,
  'deleteHotel' : ActorMethod<[bigint], undefined>,
  'deleteTrip' : ActorMethod<[bigint], undefined>,
  'fetchNews' : ActorMethod<[string], [] | [string]>,
  'getActivity' : ActorMethod<[bigint], [] | [Activity]>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllDestinations' : ActorMethod<[], Array<Destination>>,
  'getAllDorms' : ActorMethod<[], Array<Dorm>>,
  'getAllFlights' : ActorMethod<[], Array<Flight>>,
  'getAllHotels' : ActorMethod<[], Array<Hotel>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDestination' : ActorMethod<[bigint], [] | [Destination]>,
  'getDorm' : ActorMethod<[bigint], [] | [Dorm]>,
  'getFlight' : ActorMethod<[bigint], [] | [Flight]>,
  'getHotel' : ActorMethod<[bigint], [] | [Hotel]>,
  'getTravelerTrips' : ActorMethod<[], Array<Trip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateActivity' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      number,
      Array<string>,
      bigint,
    ],
    undefined
  >,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'updateDorm' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      number,
      number,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    undefined
  >,
  'updateFlight' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      string,
      bigint,
      string,
    ],
    undefined
  >,
  'updateHotel' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      number,
      number,
      Array<string>,
      Array<string>,
      bigint,
      Array<string>,
    ],
    undefined
  >,
  'updateTrip' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];